# Generated by Django 5.2.9 on 2025-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'płatność', 'verbose_name_plural': 'płatności'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekująca'), ('completed', 'Zakończona'), ('failed', 'Nieudana'), ('refunded', 'Zwrócona')], default='pending', max_length=20),
        ),
    ]
