# Generated by Django 5.2.9 on 2025-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'użytkownik', 'verbose_name_plural': 'użytkownicy'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Użytkownik'), ('admin', 'Administrator')], default='user', max_length=10),
        ),
    ]
