# Generated by Django 5.2.9 on 2025-12-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Użytkownik'), ('vendor', 'Dostawca'), ('admin', 'Administrator')], default='user', max_length=10),
        ),
    ]
