# Generated by Django 5.2.9 on 2025-12-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('access_code', models.CharField(help_text='Hasło dostępu dla rejestracji dostawcy', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'firma dostawcy',
                'verbose_name_plural': 'firmy dostawców',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='vendor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='users.vendorcompany'),
        ),
    ]
