# Generated by Django 5.2.9 on 2025-12-07 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vendorcompany_customuser_vendor_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Imię i nazwisko odbiorcy')),
                ('street', models.CharField(max_length=255, verbose_name='Ulica i numer')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('country', models.CharField(default='Polska', max_length=100, verbose_name='Kraj')),
                ('phone', models.CharField(max_length=20, verbose_name='Numer telefonu')),
                ('is_default', models.BooleanField(default=False, verbose_name='Adres domyślny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adres dostawy',
                'verbose_name_plural': 'adresy dostawy',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
