# Generated by Django 5.2.9 on 2025-12-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'koszyk', 'verbose_name_plural': 'koszyki'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'pozycja koszyka', 'verbose_name_plural': 'pozycje koszyka'},
        ),
    ]
