# Generated by Django 5.2.9 on 2025-12-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options_alter_cartitem_options'),
        ('products', '0003_product_format_product_products_pr_format_f72ff7_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_format',
            field=models.CharField(blank=True, choices=[('paperback', 'Książka papierowa'), ('ebook', 'E-book')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'selected_format')},
        ),
    ]
