# Generated by Django 5.2.9 on 2025-12-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_unique_together_and_more'),
        ('products', '0005_product_page_count_product_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'koszyk gościa',
                'verbose_name_plural': 'koszyki gości',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected_format', models.CharField(blank=True, choices=[('paperback', 'Książka papierowa'), ('ebook', 'E-book')], max_length=20, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.guestcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_cart_items', to='products.product')),
            ],
            options={
                'verbose_name': 'pozycja koszyka gościa',
                'verbose_name_plural': 'pozycje koszyka gościa',
                'unique_together': {('cart', 'product', 'selected_format')},
            },
        ),
    ]
