# Generated by Django 5.2.9 on 2025-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'zamówienie', 'verbose_name_plural': 'zamówienia'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'pozycja zamówienia', 'verbose_name_plural': 'pozycje zamówień'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Oczekująca'), ('paid', 'Opłacona'), ('failed', 'Nieudana'), ('refunded', 'Zwrócona')], default='pending', max_length=20),
        ),
    ]
