# Generated by Django 5.2.9 on 2025-12-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_format',
            field=models.CharField(blank=True, choices=[('paperback', 'Książka papierowa'), ('ebook', 'E-book')], max_length=20, null=True),
        ),
    ]
