# Generated by Django 5.2.9 on 2025-12-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_selected_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('user', 'Użytkownik'), ('guest', 'Gość')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GuestOrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Imię i nazwisko odbiorcy')),
                ('street', models.CharField(max_length=255, verbose_name='Ulica i numer')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('country', models.CharField(default='Polska', max_length=100, verbose_name='Kraj')),
                ('phone', models.CharField(max_length=20, verbose_name='Numer telefonu')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_address', to='orders.order')),
            ],
            options={
                'verbose_name': 'adres zamówienia gościa',
                'verbose_name_plural': 'adresy zamówień gości',
            },
        ),
    ]
