# Generated by Django 5.2.9 on 2025-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'produkt', 'verbose_name_plural': 'produkty'},
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fikcja'), ('non-fiction', 'Non-fiction'), ('science', 'Nauka'), ('history', 'Historia'), ('biography', 'Biografia'), ('fantasy', 'Fantasy'), ('mystery', 'Kryminał'), ('romance', 'Romans'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('self-help', 'Poradniki'), ('poetry', 'Poezja'), ('other', 'Inne')], default='other', max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['genre'], name='products_pr_genre_558550_idx'),
        ),
    ]
