# Generated by Django 5.2.9 on 2025-12-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(choices=[('paperback', 'Książka papierowa'), ('ebook', 'E-book'), ('both', 'Książka papierowa i E-book')], default='paperback', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['format'], name='products_pr_format_f72ff7_idx'),
        ),
    ]
