# Generated by Django 5.2.9 on 2025-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_format_product_products_pr_format_f72ff7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('romance', 'Romans'), ('mystery', 'Kryminał'), ('thriller', 'Thriller'), ('fantasy', 'Fantasy'), ('science-fiction', 'Science Fiction'), ('young-adult', 'Literatura młodzieżowa'), ('horror', 'Horror')], default='fantasy', max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['isbn'], name='products_pr_isbn_80a301_idx'),
        ),
    ]
