# Generated by Django 5.2.9 on 2025-12-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_page_count_product_vendor_and_more'),
        ('users', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_vendor__16bf37_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.vendorcompany'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor_company'], name='products_pr_vendor__12e5df_idx'),
        ),
    ]
